### PR TITLE
Spelling mistakes, Updated Latest Libraries, Solved Minor Warnings, Solved 1 ERR, Solved Update Endpoint Issue[simpler than #13], Minor UI fix

### PR DESCRIPTION
**Pull request by gptshubham595**
## Solved Minor Warnings

- like this
- image

## solved Map.ofEntries ERR

- Added @SuppressLint("NewApi")

## Solved  Err java.lang.ExceptionInitializeError

image

## Solved Update Endpoint Issue
- [simpler than #13 ],

### CODE REVIEW

**Comment by gptshubham595** [comment]
#hacktoberfest

**Comment by gptshubham595** [comment]
@eldadfux review this please

**Review by punitdiwan — APPROVED** [review]
Thank you @gptshubham595 for your contributions. @eldadfux we can merge the PR. @eldadfux I approve this PR.

**Comment by gptshubham595** [comment]
Do appwrite take part in GSOC? I would be happy to contribute! I love android

**Comment by gptshubham595** [comment]
@eldadfux  Please merge this !!

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Pull request merged**
